server:
  port: 9090
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://containers-us-west-136.railway.app:6513/railway
    password: qCCJrpRw8NGUIaLkmalq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect

